import '../../models/support_preset.dart';

/// All Layer 2 sensitivity toggles — shared by settings and preset configure UI.
const sensitivityToggleCatalog = <SensitivityToggle>[
  SensitivityToggle(id: 'digest_mode', displayName: 'Digest mode default', category: 'notification', description: 'Batch non-urgent notifications'),
  SensitivityToggle(id: 'reduce_notifications', displayName: 'Reduce all notifications', category: 'notification', description: 'Fewer interruptions'),
  SensitivityToggle(id: 'increase_reminders', displayName: 'Increase reminders', category: 'notification', description: 'More prompting when needed'),
  SensitivityToggle(id: 'realtime_urgent_only', displayName: 'Real-time urgent only', category: 'notification', description: 'Only urgent alerts fire immediately'),
  SensitivityToggle(id: 'quiet_hours', displayName: 'Quiet hours', category: 'notification', description: 'Mute during a set window'),
  SensitivityToggle(id: 'no_sound', displayName: 'No sound', category: 'notification', description: 'Silent alerts'),
  SensitivityToggle(id: 'no_vibration', displayName: 'No vibration', category: 'notification', description: 'Disable haptics for alerts'),
  SensitivityToggle(id: 'visual_alerts_only', displayName: 'Visual alerts only', category: 'notification', description: 'On-screen only'),
  SensitivityToggle(id: 'plain_language', displayName: 'Plain language', category: 'language', description: 'Simpler wording'),
  SensitivityToggle(id: 'extra_direct', displayName: 'Extra direct language', category: 'language', description: 'Short and clear'),
  SensitivityToggle(id: 'gentle_language', displayName: 'Gentle language', category: 'language', description: 'Softer tone'),
  SensitivityToggle(id: 'shame_free_language', displayName: 'No shame-based wording', category: 'language', description: 'Avoid guilt framing'),
  SensitivityToggle(id: 'no_diet_body', displayName: 'No diet/body language', category: 'language', description: 'Neutral body talk'),
  SensitivityToggle(id: 'no_clinical_labels', displayName: 'No clinical labels', category: 'language', description: 'Avoid diagnostic labels'),
  SensitivityToggle(id: 'no_should', displayName: 'No "should" wording', category: 'language', description: 'Reduce pressure language'),
  SensitivityToggle(id: 'no_productivity_pressure', displayName: 'No productivity pressure', category: 'language', description: 'No hustle framing'),
  SensitivityToggle(id: 'trauma_informed', displayName: 'Trauma-informed wording', category: 'language', description: 'Careful phrasing'),
  SensitivityToggle(id: 'short_prompts', displayName: 'Short prompts only', category: 'language', description: 'Brief copy'),
  SensitivityToggle(id: 'detailed_explanations', displayName: 'Detailed explanations', category: 'language', description: 'More context when asked'),
  SensitivityToggle(id: 'disable_animations', displayName: 'Disable animations', category: 'sensory', description: 'Static UI'),
  SensitivityToggle(id: 'reduce_motion', displayName: 'Reduce motion', category: 'sensory', description: 'Less movement'),
  SensitivityToggle(id: 'reduce_sound', displayName: 'Reduce sound', category: 'sensory', description: 'Quieter feedback'),
  SensitivityToggle(id: 'reduce_haptics', displayName: 'Reduce haptics', category: 'sensory', description: 'Less vibration'),
  SensitivityToggle(id: 'low_stim_theme', displayName: 'Low-stim theme', category: 'sensory', description: 'Calmer visuals'),
  SensitivityToggle(id: 'high_contrast', displayName: 'High contrast', category: 'sensory', description: 'Stronger contrast'),
  SensitivityToggle(id: 'soft_contrast', displayName: 'Soft contrast', category: 'sensory', description: 'Gentler contrast'),
  SensitivityToggle(id: 'no_flashing', displayName: 'No flashing', category: 'sensory', description: 'Avoid strobing'),
  SensitivityToggle(id: 'no_confetti', displayName: 'No confetti/celebrations', category: 'sensory', description: 'Skip celebratory effects'),
  SensitivityToggle(id: 'simplified_dashboard', displayName: 'Simplified dashboard', category: 'sensory', description: 'Fewer widgets'),
  SensitivityToggle(id: 'fewer_badges', displayName: 'Fewer badges/alerts', category: 'sensory', description: 'Less visual noise'),
  SensitivityToggle(id: 'one_next_step', displayName: 'One next step', category: 'cognitive_load', description: 'Show a single next action'),
  SensitivityToggle(id: 'hide_non_urgent', displayName: 'Hide non-urgent items', category: 'cognitive_load', description: 'Focus the list'),
  SensitivityToggle(id: 'visual_steps', displayName: 'Visual steps', category: 'cognitive_load', description: 'Step-by-step visuals'),
  SensitivityToggle(id: 'checklists', displayName: 'Checklists', category: 'cognitive_load', description: 'Checklist format'),
  SensitivityToggle(id: 'short_summaries', displayName: 'Short summaries', category: 'cognitive_load', description: 'Brief digests'),
  SensitivityToggle(id: 'explain_simply', displayName: '"Explain this simply"', category: 'cognitive_load', description: 'Plain explanations'),
  SensitivityToggle(id: 'memory_prompts', displayName: 'Memory prompts', category: 'cognitive_load', description: 'Gentle reminders'),
  SensitivityToggle(id: 'routine_support', displayName: 'Routine support', category: 'cognitive_load', description: 'Routine scaffolding'),
  SensitivityToggle(id: 'fewer_choices', displayName: 'Fewer choices', category: 'cognitive_load', description: 'Reduce options'),
  SensitivityToggle(id: 'one_recommendation', displayName: 'Default to one recommendation', category: 'cognitive_load', description: 'Single suggestion'),
  SensitivityToggle(id: 'keep_messy_capture', displayName: 'Keep original messy capture', category: 'cognitive_load', description: 'Preserve raw notes'),
  SensitivityToggle(id: 'avoid_calories', displayName: 'Avoid calories', category: 'food_body', description: 'Hide calorie counts'),
  SensitivityToggle(id: 'hide_weight', displayName: 'Hide weight', category: 'food_body', description: 'No weight displays'),
  SensitivityToggle(id: 'no_good_bad_food', displayName: 'No good/bad food language', category: 'food_body', description: 'Neutral food talk'),
  SensitivityToggle(id: 'no_diet_culture', displayName: 'No diet culture language', category: 'food_body', description: 'Avoid diet framing'),
  SensitivityToggle(id: 'no_weight_loss', displayName: 'No weight-loss prompts', category: 'food_body', description: 'Skip weight goals'),
  SensitivityToggle(id: 'no_exercise_punishment', displayName: 'No exercise-as-punishment', category: 'food_body', description: 'Neutral movement'),
  SensitivityToggle(id: 'neutral_meal_reminders', displayName: 'Neutral meal reminders', category: 'food_body', description: 'Gentle meal nudges'),
  SensitivityToggle(id: 'safe_foods', displayName: 'Safe foods list', category: 'food_body', description: 'Track safe foods'),
  SensitivityToggle(id: 'sensory_foods', displayName: 'Sensory foods support', category: 'food_body', description: 'Texture-aware support'),
  SensitivityToggle(id: 'arfid_support', displayName: 'ARFID support', category: 'food_body', description: 'ARFID-aware prompts'),
  SensitivityToggle(id: 'distress_after_meals', displayName: 'Distress-after-meals support', category: 'food_body', description: 'Post-meal care'),
  SensitivityToggle(id: 'pause_before_send', displayName: 'Pause before sending', category: 'communication', description: 'Confirm before send'),
  SensitivityToggle(id: 'require_send_confirm', displayName: 'Require confirmation to send', category: 'communication', description: 'Extra confirm step'),
  SensitivityToggle(id: 'cooling_off', displayName: 'Cooling-off timer', category: 'communication', description: 'Delay before send'),
  SensitivityToggle(id: 'draft_only', displayName: "Draft only, don't send", category: 'communication', description: 'Keep as draft'),
  SensitivityToggle(id: 'one_draft', displayName: 'One draft, not five', category: 'communication', description: 'Limit draft variants'),
  SensitivityToggle(id: 'tone_check', displayName: 'Tone check', category: 'communication', description: 'Review tone before send'),
  SensitivityToggle(id: 'conflict_deescalation', displayName: 'Conflict de-escalation', category: 'communication', description: 'Softer conflict prompts'),
  SensitivityToggle(id: 'repair_prompt', displayName: 'Repair prompt', category: 'communication', description: 'Suggest repair language'),
  SensitivityToggle(id: 'trusted_checkin', displayName: 'Trusted-person check-in', category: 'communication', description: 'Ping a trusted person'),
  SensitivityToggle(id: 'hide_suggestions_overwhelm', displayName: 'Hide message suggestions during overwhelm', category: 'communication', description: 'Silence suggestions'),
  SensitivityToggle(id: 'confirm_spend', displayName: 'Require confirmation to spend', category: 'financial', description: 'Confirm before logging spend'),
  SensitivityToggle(id: 'delay_big_decisions', displayName: 'Delay big financial decisions', category: 'financial', description: 'Cooling-off for money'),
  SensitivityToggle(id: 'avoid_shame_spend', displayName: 'Avoid shame spending language', category: 'financial', description: 'Neutral money talk'),
  SensitivityToggle(id: 'bare_minimum_budget', displayName: 'Bare-minimum budget mode', category: 'financial', description: 'Essentials only'),
  SensitivityToggle(id: 'bill_warning', displayName: 'Bill warning mode', category: 'financial', description: 'Highlight upcoming bills'),
  SensitivityToggle(id: 'sinking_fund_suggestions', displayName: 'Sinking fund suggestions', category: 'financial', description: 'Suggest savings pots'),
  SensitivityToggle(id: 'visual_budget_bars', displayName: 'Visual budget bars', category: 'financial', description: 'Bar-based view'),
  SensitivityToggle(id: 'simplified_numbers', displayName: 'Simplified numbers', category: 'financial', description: 'Round / simplify'),
  SensitivityToggle(id: 'reduce_impulse', displayName: 'Reduce impulse-purchase prompts', category: 'financial', description: 'Fewer buy nudges'),
  SensitivityToggle(id: 'med_reminders', displayName: 'Medication reminders', category: 'health', description: 'Med timing prompts'),
  SensitivityToggle(id: 'appointment_prep', displayName: 'Appointment prep', category: 'health', description: 'Prep checklists'),
  SensitivityToggle(id: 'symptom_logging', displayName: 'Symptom logging', category: 'health', description: 'Quick symptom capture'),
  SensitivityToggle(id: 'doctor_export', displayName: 'Doctor export', category: 'health', description: 'Export for clinicians'),
  SensitivityToggle(id: 'low_energy_mode', displayName: 'Low-energy mode', category: 'health', description: 'Reduce demands'),
  SensitivityToggle(id: 'flare_mode', displayName: 'Flare mode', category: 'health', description: 'Flare-day support'),
  SensitivityToggle(id: 'pain_day_mode', displayName: 'Pain day mode', category: 'health', description: 'Pain-day support'),
  SensitivityToggle(id: 'migraine_mode', displayName: 'Migraine mode', category: 'health', description: 'Migraine support'),
  SensitivityToggle(id: 'post_seizure_mode', displayName: 'Post-seizure mode', category: 'health', description: 'Recovery mode'),
  SensitivityToggle(id: 'pregnancy_postpartum', displayName: 'Pregnancy/postpartum sensitivity', category: 'health', description: 'Perinatal-aware UI'),
  SensitivityToggle(id: 'hide_sensitive_notes', displayName: 'Hide sensitive notes', category: 'privacy', description: 'Mask sensitive content'),
  SensitivityToggle(id: 'require_app_lock', displayName: 'Require app lock', category: 'privacy', description: 'PIN / biometric'),
  SensitivityToggle(id: 'private_chat', displayName: 'Private chat mode', category: 'privacy', description: 'Private conversations'),
  SensitivityToggle(id: 'exclude_ai_summaries', displayName: 'Exclude from AI summaries', category: 'privacy', description: 'Skip in digests'),
  SensitivityToggle(id: 'exclude_partner_sharing', displayName: 'Exclude from partner sharing', category: 'privacy', description: 'Keep local'),
  SensitivityToggle(id: 'hide_from_dashboard', displayName: 'Hide from dashboard', category: 'privacy', description: 'No dashboard surface'),
  SensitivityToggle(id: 'visible_only_user', displayName: 'Visible only to user', category: 'privacy', description: 'Owner-only visibility'),
  SensitivityToggle(id: 'auto_delete', displayName: 'Auto-delete after set period', category: 'privacy', description: 'Timed retention'),
];

const sensitivityToggleCategoryLabels = <String, String>{
  'notification': 'Notification sensitivity',
  'language': 'Language sensitivity',
  'sensory': 'Sensory sensitivity',
  'cognitive_load': 'Cognitive load sensitivity',
  'food_body': 'Food / body sensitivity',
  'communication': 'Communication sensitivity',
  'financial': 'Financial sensitivity',
  'health': 'Health sensitivity',
  'privacy': 'Privacy sensitivity',
};

SensitivityToggle? sensitivityToggleById(String id) {
  for (final t in sensitivityToggleCatalog) {
    if (t.id == id) return t;
  }
  return null;
}
